# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yyjyxt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yyjyxt
pod 'AFNetworking', '~> 3.1.0'
pod 'YYModel', '~> 1.0.4'
pod 'YYCache', '~> 1.0.4'
pod 'IQKeyboardManager', '~> 4.0.9'
end
